# API Configuration
api:
  model: "claude-sonnet-4"
  max_tokens: 4096
  temperature: 0.0

# Evaluation Thresholds
thresholds:
  confidence_threshold: 0.7
  statistical_significance: 0.05
  min_sample_size: 30

# Orchestration
orchestration:
  max_replans: 2
  timeout_seconds: 300
  
# Logging
logging:
  level: "INFO"
  format: "json"
  save_to_file: true
